config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end


  root "homes#top"

  get "/home/about" => "homes#about"
  resources :users
  resources :books do
    resources :post_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :profile_image
  has_many :post_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post_image.rb
class PostImage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, presence: true, length: { minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :public_action]
  before_action :configure_permitted_parameters,if: :devise_controller?

    def after_sign_out_path_for(resource)
      root_path
    end

    def after_sign_in_path_for(resource)
	  user_path(resource)
    end

  private
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @post_comment = PostComment.new
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = @book.id
    comment.save
    redirect_to book_path(@book)
  end
  
  def destroy
    comment = PostComment.find(params[:id])
    comment.destroy
    redirect_to book_path(comment.book_id) # 正しくリダイレクト
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%= form_with(model: book, local: true) do |f| %>
  <div class="form-title row">
    <%= f.label :Title %>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-body row">
  	<%= f.label :Opinion %>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions row">
    <%= f.submit class: "btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="box2">
  <h1>Editing Book</h1>
  <%= form_with(model: @book, url: book_path(@book.id), local: true) do |f| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h4>Title</h4>
    <%= f.text_field :title, class: "col-xs-12" %>
    <h4>Opinion</h4>
    <%= f.text_area :body, class: "col-xs-12" %>

    <nav>
      <%= f.submit 'Update Book', class: "col-xs-12 btn btn-primary" %>
    </nav>
  <% end %>

  <%= link_to "Show", book_path(@book.id) %> |
  <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <!--<div class="box">-->
        <%= render 'users/user', user: @user %>
        <!-- form_with部分 -->
        <%= form_with(model: @book, url: books_path, local: true) do |f| %>
          <% if @book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <h2>New book</h2>
          <h4>Title</h4>
          <%= f.text_field :title, class: "form-control" %>

          <h4>Opinion</h4>
          <%= f.text_area :body, class: "form-control" %>

          <nav>
            <%= f.submit 'Create Book', class: "btn btn-primary mt-3" %>
          </nav>
        <% end %>
      <!--</div>-->
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <% if book.user.profile_image.attached? %>
                    <%= image_tag book.user.profile_image.variant(resize_to_fill: [50, 50]) %>
                  <% else %>
                    <%= image_tag "no_image.jpg", size: "50x50" %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><p><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></p></td>
            </tr>
            
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="box">
        <% if @book.errors.any? %>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= render 'users/user', user: @user %>

        <!-- form_with部分 -->
        <%= form_with(model: @book_new, url: books_path, local: true) do |f| %>
          <h2>New book</h2>
          <h4>Title</h4>
          <%= f.text_field :title, class: "form-control" %>

          <h4>Opinion</h4>
          <%= f.text_field :body, class: "form-control" %>

          <nav>
            <%= f.submit 'Create Book', class: "btn btn-primary mt-3" %>
          </nav>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <% if @user.profile_image.attached? %>
                <%= image_tag @user.profile_image.variant(resize_to_fill: [50, 50]) %>
              <% else %>
                <%= image_tag 'no_image.jpg', size: '50x50' %>
              <% end %>
              <nav>
                <%= @user.name %>
              </nav>
            <% end %>
          </td>

          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>

          <% if @book.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      
      <div>
  <p>コメント件数：<%= @book.post_comments.count %></p>
 <% @book.post_comments.each do |post_comment| %>
  <p><%= image_tag post_comment.user.get_profile_image(100, 100) if post_comment.user %></p>
  <p><%= post_comment.user.name %></p>
  <% if post_comment.created_at.present? %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% else %>
    <p>作成日時不明</p>
  <% end %>
  <% if post_comment.user == current_user %>
      <%= link_to "削除", book_post_comment_path(post_comment.book, post_comment), method: :delete %>
    <% end %>
  
<% end %>

</div>
<div>
  <%= form_with model: [@book, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>welcome to
  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
  <b><i class="fa-solid fa-book"></i>Bookers!</b>



</h1>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
	<div class="col-md-6 col-md-offset-3">
	  <div class="top-text">
		<h1>Welcome to
		  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
		  <i class="fa-solid fa-book"></i><b>Bookers!!</b>
		</h1>
		<p>In
		  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
		  <i class="fa-solid fa-book"></i><b>Bookers</b>,<br>
		  	you can share and exchange your opinions , inpresiions , and emotions<br>
		  	about various books!
		</p>
	  </div>
	<div class="row">
      <%= link_to "Log in", new_user_session_path, class:"btn btn-primary col-xs-10 col-xs-offset-1" %>
	</div>
	<div class="row">
	  <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1" %>
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <script src="https://kit.fontawesome.com/88c8c0fbe8.js" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  
  
</head>


<body>
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#">Bookers</a>
  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to user_path(current_user.id), class: 'nav-link' do %>
            <i class="fa-solid fa-house"></i> Home
            <% end %>
            </li>

            <li class="nav-item">
              <%= link_to "/users", class: 'nav-link' do %>
              <i class="fa-solid fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "/books", class: 'nav-link' do %>
              <i class="fa-solid fa-book-open"></i> Books
            <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
              <i class="fa-solid fa-right-from-bracket"></i> Log out
            <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link' do %>
              <i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path, class: 'nav-link' do %>
              <i class="fa-solid fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link' do %>
              <i class="fa-solid fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link' do %>
              <i class="fa-solid fa-right-to-bracket"></i> Log in
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>


  <div class="body">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
  </div>

  <%= yield %>

  <footer>
    <div class='container'>
      <div class='row'>
        <div class='col-xs-3 col-xs-offset-9'>
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

app/views/users/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this <%= model.class.name.downcase %> from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="container">
  <!-- User Info Section -->
  <div class="user-info">
    <h2>User info</h2>
    <div class="user-info-content">
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image.variant(resize_to_fill: [100, 100]), class: "profile-image" %>
      <% else %>
        <%= image_tag "no_image.jpg", size: "100x100", class: "profile-image" %>
      <% end %>
      <div class="user-details">
        <div class="detail-item">
          <strong>name</strong>
          <span><strong><%= @user.name %></strong></span>
        </div>
        <div class="detail-item">
          <strong>introduction</strong>
          <span><strong><%= @user.introduction %></strong></span>
        </div>
      </div>
    </div>
<%= link_to edit_user_path(@user.id), class: "btn btn-user-edit" do %>
  <i class="fas fa-user-cog"></i> 
<% end %>
  </div>

  

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'error_messages', model: @user %> <!-- ここでパーシャルをレンダリング -->
　
  <div class="user-name">Name</div>
  <%= f.text_field :name %>

  <div class="user-edit-image">Image</div>
  <%= f.file_field :profile_image %>

  <div class="form-body">Introduction</div>
  <%= f.text_area :introduction %><br>

  <div class="upload">
    <%= f.submit "Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <!-- User info と New book を含むカラム -->
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    
    <!-- Users を表示するカラム -->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-sm user-index">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <% if user.profile_image.attached? %>
                  <%= image_tag user.profile_image.variant(resize_to_fill: [50, 50]) %>
                <% else %>
                  <%= image_tag "no_image.jpg", size: "50x50" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-user-show">
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <% if @user.profile_image.attached? %>
                  <%= image_tag @user.profile_image.variant(resize_to_fill: [50, 50]) %>
                <% else %>
                  <%= image_tag "no_image.jpg", size: "50x50" %>
                <% end %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
           <p><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></p>
        <% end %>
      </table>
    </div>
  </div>
</div>